name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release --self-contained -r win-x64 -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload SKCASE5 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SKCASE5
        path: /home/runner/work/Suleman-Khan-Case-Study-5-Dev-Ops/Suleman-Khan-Case-Study-5-Dev-Ops/bin/Release/net5.0/win-x64/publish/
